### ISSUE TITLE
Home Assistant 0.110 - ClimateDevice/BinarySensorDevice is deprecated

### ISSUE THREAD

**Issue by oopiicaa** [koleo9am/hass_max_home_automation#12]
As of Home Assistant 0.110 (currently running 0.110.1) this appears in the log:
`ClimateDevice is deprecated, modify MaxHomeAutomationClimate to extend ClimateEntity
08:34:06 – Climate (WARNING)`

**Comment by oopiicaa** [comment]
And also this (did not notice it before, but did now after upgrading to 0.110.2):
2020-05-25 08:36:49 WARNING (MainThread) [homeassistant.components.binary_sensor] BinarySensorDevice is deprecated, modify MaxHomeAutomationBinarySensor to extend BinarySensorEntity

**Comment by peterhaaf** [comment]
Hi,

did you find time to fix this ? I would l like to give max home automation using rest calls a try ...

Best

**Comment by oopiicaa** [comment]
Nope, sorry. I've deprecated my MAX! valves in the meantime and switched to Zigbee ones.

**Comment by tiger42** [comment]
Fixed in master
