### ISSUE TITLE
Error in install

### ISSUE THREAD

**Issue by vitbut** [koleo9am/hass_max_home_automation#15]
Hello,

I've got a error, when I tried to set up integration:

Component error: maxhomeautomation - cannot import name 'STATE_AUTO' from 'homeassistant.components.climate.const' (/usr/src/homeassistant/homeassistant/components/climate/const.py)

Could anybody help, please.
Thanks,
Regards,
Vitali

**Comment by koleo9am** [comment]
Hi, it looks like you have older version of sources. Getting current ones from github will solve your problem.
