### ISSUE TITLE
Changing temperature in AUTO mode

### ISSUE THREAD

**Issue by banolka** [koleo9am/hass_max_home_automation#4]
Hi, I was able to setup the file and is working but I found one problem When Termostat is in AUTO mode changing temperature is not allowed. Is it possible to fix or implement this feature?

**Comment by koleo9am** [comment]
With the Thermostat you mean wall thermostat? I have no wall thermostat so I didn't know abou this behaviour.
How do you expect it to work? Is an user warning suficient?

Thx.

**Comment by koleo9am** [comment]
And what about other operation modes? Does ECO behave same as AUTO?

**Comment by banolka** [comment]
Hi, I have only radiator_thermostats.

I checked AUTO and ECO mode and the change of temperature value on the HA - climate component is not working. When I switch to manual mode i can adjust the tempereture value.

I think no need to have any notification just to allow for such changes.

When I'm using MAX! app when temp value is changed i AUTO mode it will be only changed to the next set point in time so for few hours in my case. I think it would be nice to have this working if possible :)

In the future I will think also on the templates to allow some presets for example set desired temp setting to dry  laundry in the laundry room :)

On the last note here is awesome simple and customizable termostat for HA -https://github.com/nervetattoo/simple-thermostat

![FireShot Capture 010 - Home Assistant - 192 168 1 39](https://user-images.githubusercontent.com/45588903/55003265-59d25e80-4fd8-11e9-8b52-3155b943468a.png)

**Comment by koleo9am** [comment]
Corrected for AUTO mode in revision 99788f1. This was a bug.

**Comment by koleo9am** [comment]
ECO and BOOST modes follows the radiator thermostat settings. There is no way to set it via max_home_automation. I'll try to disable target temperature feature based on operation mode - hope HA will follow it during runtime.

**Comment by koleo9am** [comment]
About the laundry room - you can write automation script to do so. There is not necesary to change the climate component.
